### ISSUE TITLE
Allow Gerby to use upstream plasTeX

### ISSUE THREAD

**Issue by PatrickMassot** [plastex/plastex#160]
The [stacks project](https://stacks.math.columbia.edu/) uses plasTeX for rendering with a [very unusual workflow](https://gerby-project.github.io/). They currently use a [plasTeX fork](https://github.com/gerby-project/plastex) whereas they should be able to use upstream plasTeX with a custom renderer and cli. This is issue is a specific milestone for #159

**Comment by dalcde** [comment]
This is a list of all gerby commits as of 2020-04-20, minus some I know have been upstreamed/are irrelevant. A commit is considered irrelevant if it only affects things in the Gerby renderer or the HTML5 renderer (which afaik Gerby doesn't use). There is I believe a large number of commits here that are irrelevant in this sense, but I haven't gone through all of them

 - [ ] Started linking labels and tags in the DOM tree 7033c96
 - [ ] Detects tags at Renderable.__str__ level 9b06d06
 - [ ] Copying and modifying the bare essentials of HTML5 639c295
 - [ ] Started a Gerby configuration file de294e9
 - [ ] Use plasTeX's output routine to generate files 39c8750
 - [ ] Implemented the marginnote package 1339535
 - [ ] Fixed filename generator 947783d
 - [ ] Partial statement finder for proofs b76327e
 - [ ] Made searchTheorem a static method 992f502
 - [ ] Implemented output propagation 7f7fa2b
 - [ ] Moved tags to userdata b696355
 - [ ] No file extensions for proofs b169a6f
 - [ ] Code cleanup and \ref in proof caption matching 5a3ec72
 - [ ] Make \cite handling more stupid abc268d
 - [ ] Adding slogan environment 103b7f4
 - [ ] Less clutter files by setting split-level option 2c87cf8
 - [ ] Improved templates bb3f774
 - [ ] Using file extensions for output 5576ddd
 - [ ] Handling slogans 3a87e34
 - [ ] Implement history environment 3d43dfb
 - [ ] Fixed silly template issue 4b85205
 - [ ] Small output changes aa226d2
 - [ ] Reordered some lines a9c66f6
 - [ ] Changed theorem template 42caca0
 - [ ] Temporarily fixing Jacob's multi-file indexing 1e0f757
 - [ ] Fixes #2 67f98b3
 - [ ] Fixes #5 0f1f235
 - [ ] Fixes #3 992df1b
 - [ ] Ability to add custom markers and change default style to match LaTeX.  717ba0e
 - [ ] Removing theme files 8ecd79e
 - [ ] Potential solution for footnotes.  5e6be2d
 - [ ] Should check that there are footnotes.  5eed464
 - [ ] Implement romannumeral.  4dbe830
 - [ ] Fixes #4 4176b6a
 - [ ] Updated footnote template 9cc4ec3
 - [ ] Fixes #8 8672726
 - [ ] New Command class so arguments have no charsub.  8498571
 - [ ] Outputting the tree structure for debugging a7b3772
 - [ ] Make sure the EndRow argument for matrix environments leaves initial … 8f98825
 - [ ] Spacing variants for xypic.  6a8f182
 - [ ] Small hack to make plasTeX not put a space after \omit.  a24e7c0
 - [ ] Adding data attribute to references ac0226c
 - [ ] Less ambiguous li output 3b50b30
 - [ ] Don't propagate headings f025bce
 - [ ] Fixes bad li template 091956b
 - [ ] Possible fix for #15 9f7bb50
 - [ ] Adding data-tag on sectioning commands 4762632
 - [ ] Fixes #24 and #26 dd605b0
 - [ ] Place proof header and QED square inside paragraph elements of a proof.  35d00d9
 - [ ] Not just equation should be numbered 4d1c25b
 - [ ] Chapter counter shouldn't reset with new part 9f67ca3
 - [ ] Removing custom invoke on index bf4a617
 - [ ] Write parts and chapters to JSON file b3fff6a
 - [ ] Don't try parts if there are none 63047d3
 - [ ] Slogans etc. are associated to parent node c9dfd3e
 - [ ] There are also references in the Stacks project 17c2601
 - [ ] Copying bibliography files to output 73b4b5d
 - [ ] Dealing with references 6572b72
 - [ ] Fixes #37 a0abec7
 - [ ] Getting rid of extra whitespace in citations 495d0fb
 - [ ] No character substitutions in math environments.  bcb2524
 - [ ] New xymatrix variant found in SAG.  df5178c
 - [ ] Fix spacing and reference issues in thmenv.  0e224ba
 - [ ] Implements optional parameter for cite, #44 bac5e9d
 - [ ] Gets rid of mysterious hack from 1e0f757 6f4be32
 - [ ] Remove debugger import.  ac04f9a
 - [ ] Make slogans and history elements also whitespace.  e857e04
 - [ ] Add meta information into Context; in particular, line count.  eae2c93
 - [ ] Remove irrelevant TODOs.  6fbdc58
 - [ ] reversed is necessary because...  7da553e
 - [ ] Revert "reversed is necessary because..." bb38d1f
 - [ ] Woops, revert killed too much; just got rid of debugger.  00ebf1b
 - [ ] Allow alignment tags inside xymatrix.  e306640
 - [ ] Tags for enumerate items.  bcd8d94
 - [ ] Refactor the character substitution to a flag.  b65433a
 - [ ] Further things that should not do charSubs.  1a21e0c
 - [ ] No character substitutions in math mode.  3722774
 - [ ] Remove extra paragraph tags around displaymath divs.  ea09c79
 - [ ] Wrapping postnote of a citation in a <span> 2ecf68e
 - [ ] Fixing silly HTML issue in previous commit 54ce409
 - [ ] Don't use data-marker on list items with tags 030308c
 - [ ] Fixes #49 fa3cf47
 - [ ] Fixes #48.  8f2a8d5
 - [ ] Implements #43.  2bb10f0
 - [ ] Implements #25.  762f8d0
 - [ ] Add dictionary that keeps track of individual arguments.  4b36f93
 - [ ] Fix a woopsie on variable names; also, periods are confusing.  9c510b6
 - [ ] Define skeletal commands for xyoption and UseAllTwocells to stop comp… 09d27bb
 - [ ] Implement template for href.  dccb21d
 - [ ] Allow bfseries, textbf, itseries, textit in font selection.  af477ad
 - [ ] Some templates for alignments.  c13e3f1
 - [ ] Template for large command.  8a71752
 - [ ] Template for quote environment.  f524566
 - [ ] Template to print out reference, slogan, history things.  a79a99f
 - [ ] Stop Gerby from complaining about bigskip, bibliography, and bibliogr… 592489d
 - [ ] No data-tag for tagged items; no tag toggling for items for now.  add7b63
 - [ ] Add text command into FontSelections.  ebb8c51
 - [ ] Fixes unknown datatype in hyperref implementation c576c7d
 - [ ] Use caption, not thmName, for naming thmenv's 0beb15b
 - [ ] Parts are by default numbered using Roman d657a30
 - [ ] Make sure that <, > are wrapped in spaces in math ebc152d
 - [ ] Undo previous commit a313ccd
 - [ ] Revert "Parts are by default numbered using Roman" 5503a35
 - [ ] Remove one character from a re.compile expression cd87e57
 - [ ] Strip HTML for item marker in template abcdd54
 - [ ] Sometimes a proof does not have a caption 5c274c9
 - [ ] Implemented 'gathered' environment 2c34245

**Comment by pbelmans** [comment]
This is the appropriate location to apologise for all the ugly hacks and uninformed fixes, I guess...

Thanks for all this hard work!

**Comment by PatrickMassot** [comment]
@dalcde is the above checklist up to date?

**Comment by dalcde** [comment]
I believe so

**Comment by PatrickMassot** [comment]
Thanks. I removed a couple of irrelevant items.

**Comment by PatrickMassot** [comment]
How did you manage to bring those Gerby commits without putting them in a branch? I'd like to cherry-pick some of them but I don't know how to get them locally.

**Comment by dalcde** [comment]
I fetch the repo to my local copy of plastex. They are still somewhat
compatible

**Comment by kno10** [comment]
Some of the "Charsub related" changes have been merged if I am not mistaken?

**Comment by stephengaito** [comment]
I would very much like to use PlasTeX/Gerby for my own project.

However I have been having trouble running the Gerby-project's version of PlasTeX with modern Python tools.

Hence I have started a project [diSimplex/plastex-gerby-plugin](https://github.com/diSimplex/plastex-gerby-plugin) whose aim is to provide the Gerby project's Renderer code as a "native" PlasTeX plugin. (See: #358 / #359 / #360 / #361 ) 

(I suspect that I *might* be a "Fool rushing in where Angles fear to tread"... however, your tools are very useful and I would like to see them continue! )

I can "load" my proposed plugin, and I am now finding changes Gerby has made to the base PlasTeX code to support their needs. 

For example I am have currently "stumbled" upon "Add meta information into Context; in particular, line count. https://github.com/plastex/plastex/commit/eae2c937ad18b12127553ec22ce46a43344e4be7".

---

@PatrickMassot and @pbelmans : what is stopping these back-ports from happening?

_**More to the point how can I help get some of these back-ports tested and accepted?**_
